dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: qbpRZlzCKiBEs66B7/oe/CsL42B4sF1JbqWkYd1I0Nz6NtjGMd1GRl3La9MH0tesAyVPFr7uU5b4yExOSeW7jWtDiu9Ou/kGjgfoFHFeyww0rPYctCmwdF/RFSNuyh82gBtzPI4KCuhGZp0qSrPFlf5c4QLsPy6bn1mc9bXf+iipWBL14IfhJRG41jVcn5PeWDbyj2sMNmcOVi8fUGLQ7/yAuvNlB6yGwzkUH+9ZwoZ+MEtGbH3WbpegmwU2YVrU4zOvEY0rIBjCo1UQ2mQxbDObcZoX9Bmp8H6pJPcABCr77zyewSpVvxduZGCRAEB9uguKHZu5yY4t0fUQEgEtDAQ2DzsXeDsreGUdDcWsta20/bR1tXoLXt/7Te15148c/BjUylTBNaNfM3TuGIkEcTagqapqX8Ryx6YfgbLiuXET8sWQ9a6pqn2+asgRlKKjq6fu3QRbhYD0ZUs1X7giGuC6uiVLNd85iabnx5BMHWCnrKpPAyaQVn2Ieq/cjiS23nR3z6Czj5PAie7Bq/u9RAFlvP19wdYQUwV5mFXD5T9Uqb9PPwyxO6XqpzEnr9zzHftkskduMn30ddEhs6KghzscRkdL3g+J0s62N7/TL3TRW4yALfWvAc2P90kUwKRp4Y+05Vp8czkelF/hxXgyUqSC6zucyoxDz/3arifjusE=
