dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: jnWo+Qb5sObZDEK0ZsURrbQZoHkteGp0wdNdvWNRdtQdyDE9ZIk/C3o2ysBx+zVJEv26++y9whsYHrYtfWFJ5SEB+wfumiBhdmr+wi7pgHwJ8rJQYu95w28f4lRx48qoqd4qyJWXVYeBaJkTzHsNHOEZ1MQAxshejDQbm7huS/vz+WuUZszQHPlwRy/WqUaPYi7QOXkFtmNuMZRPN7IcrX+7c3Gkiv062e1hfQkCHBJhE5Xh2nJ7+YL90VC7B+e8oPeO1rwNmzGLGfOBKgN3/sR87SORFfWlumPTck1mysHrj1nsq1sYpazmv6WdGV3/neYfV5XhM0V8kleshAMW/bSZyQHrhNCQDEL5+sX9OGtnaAiGhUD2pYAIPOp2J77BCVzfSqmL8OC3eaEcZvoNNHdrRBMRcpGNdimxKPncQuImUoJwVdrKGJ0iYnCRMIQ95ewlnC9+/Q7oZMm34mqp2YRqfl3RcU/doYkTlY7pfp2xnh6cha9x62R+4EaR80KTpbzhV1nftWPSEB2+gTB3PsxuLQFDXruNkk8tKWTVw4hCuD5Oqvf8kk6ELXAmuoELheUPogMQWPIXv2DNk7Ya/TPZjPS+qDHhFGHALvGF4YOcy7+fTJlKlTs2ZpWuVdKmV6yuvaGM9gA89M0nfUV2z+NYoXZcJIDHoLN9PSmDczo=
