dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
dd:
  secure: bb8QehimVFc/TD1V1AiKklKHuwvQ8wLUOE/gU96utfd+cjpT/eCxXcFUOKtXtegC5E3tyWiziqGhprCto0dV8LQxuTTH7X4tV6cmvcqD5Ox3CpIPpn0WueCQ0FT0V6a31nLVrzh/7UqV90bY6OJ777xRYq1gwhvN+OjunI/il9gwg6vXPExaxOIX1NPX7G7m1U3i+77EkkvqkpQLNWH1y6siMLlMsswG9+CpJMIuhIPpD1AKRCBnBUKOySL7W4ea+asW/q/LqCCQHq1m7EWNEc37xMBLRsiU/kdu097FQtRLMuM2isMIF3Y60yT5MZw1YMWhP/75D5hFHBGOQEGjhMW+L4Ly+nVO9ajB3Ssu8Mw5krnU8cebZSnSOLHw+gU+qdp+rl9krBAEgxF6I0lr75Br4m2T7Hqsus2iw1VkWuoUFiioXmcfYqFnltPxtkv4oixU0y4PALS24JT0pwtq7B0sUOdrEwsM0ubrkFaGyD3HCD/nOcvJz5KKw9h6/FmVUz8hn4v2/18zWgqAWYOHczHQhnD6SsRaGYzLNNi8pjGjxIfPWlqGd3HFrM633C+uUh73QzxAGOBxiBYuPxwTcG3lFmkibC/usrotXJbmyQhD+9m6TGkffhsCK+3KrGeZHOh5djGdZ/x9jUKqQpPEhHgi0SfWgieJLJ3zrndrBSA=
